base: &base_config
  decay_rate: 0.995
  fraction_fit: 0.5
  fraction_evaluate: 0.0
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2
  learning_rate: 0.01
  num_rounds: 200
  num_clients: 60
  local_training_epochs: 5
  batch_size: 32
  seed_value: 42 
  partition_fraction: [0.3, 0.3, 0.3, 0.1]
  partition_alpha: [0.01, 0.05, 0.1, 100] 

fedavg: 
  <<: *base_config

fedadp: 
  <<: *base_config
  alpha: 5

fedimp: 
  <<: *base_config
  temperature: 0.7 

fedcls: 
  <<: *base_config
  alpha: 0.5 

feddisco: 
  <<: *base_config
  alpha: 0.5
  beta:  0.1

fedntd: 
  <<: *base_config
  tau: 3
  beta: 1

moon:
  <<: *base_config
  temperature: 1.5

scaffold:
  <<: *base_config
  